name: Run Compatibility Test

on:
  repository_dispatch:
    types: RunCompatibilityTest

jobs:
  stackTest:
    name: Compatibility test for service:${{ github.event.client_payload.service }} version:${{ github.event.client_payload.version }} pluginSha:${{ github.event.client_payload.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            17
          distribution: 'zulu'
          cache: 'gradle'

      - name: run tests
        uses: armory-io/plugin-test-runner@a2340cc9cf88bffe55484e072d6ca845fd204d82 # main
        env:
          ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_TOKEN }}
        with:
          service: ${{ github.event.client_payload.service }}
          version: ${{ github.event.client_payload.version }}
          plugin_sha: ${{ github.event.client_payload.sha }}
